{% set name = "m2w64-sysroot" %}

package:
  name: {{ name|lower }}
  version: {{ GIT_DESCRIBE_TAG[1:] }}.r{{ GIT_DESCRIBE_NUMBER }}.g{{ GIT_DESCRIBE_HASH }}

source:
  git_url: https://github.com/mingw-w64/mingw-w64
  git_rev: dc42231f0
  patches:
    - 0001-Allow-to-use-bessel-and-complex-functions-without-un.patch
    - 0002-heades-add-full-name-winrt.patch

build:
  number: 6

requirements:
  build:
    - gcc_bootstrap_win-64
    - make
  host:
    # Add a package here to prevent build host merge
    - tzdata
  run:

test:
  commands:
    - echo "hello"

outputs:
  - name: mingw-w64-ucrt-x86_64-headers-git
    script: install.sh
    files:
      - x86_64-w64-mingw32/sysroot/usr/include
      - Library/x86_64-w64-mingw32/sysroot/usr/include
    build:
      noarch: generic
    requirements:
      build:
        - gcc_bootstrap_win-64
        - make
      host:
        # Add a package here to prevent build host merge
        - tzdata
      run:
        - __unix   # [unix]
        - __win    # [win]
      run_constrained:
        - mingw-w64-ucrt-x86_64-crt-git {{ PKG_VERSION }}.*
        - mingw-w64-ucrt-x86_64-winpthreads-git {{ PKG_VERSION }}.*
    about:
      home: https://www.mingw-w64.org/
      license: ZPL-2.1 AND LGPL-2.1-or-later
      license_file:
        - mingw-w64-headers/ddk/readme.txt
        - COPYING
        - COPYING.MinGW-w64/COPYING.MinGW-w64.txt
      summary: |
        MinGW-w64 headers for Windows (mingw-w64)

  - name: mingw-w64-ucrt-x86_64-winpthreads-git
    script: install.sh
    files:
      - x86_64-w64-mingw32/sysroot/usr/include/semaphore.h
      - x86_64-w64-mingw32/sysroot/usr/include/sched.h
      - x86_64-w64-mingw32/sysroot/usr/include/pthread*.h
      - x86_64-w64-mingw32/sysroot/usr/lib/lib*pthread*.a
      - Library/x86_64-w64-mingw32/sysroot/usr/include/semaphore.h
      - Library/x86_64-w64-mingw32/sysroot/usr/include/sched.h
      - Library/x86_64-w64-mingw32/sysroot/usr/include/pthread*.h
      - Library/x86_64-w64-mingw32/sysroot/usr/lib/lib*pthread*.a
    build:
      noarch: generic
    requirements:
      build:
        - gcc_bootstrap_win-64
        - make
      host:
        # Add a package here to prevent build host merge
        - tzdata
      run:
        - {{ pin_subpackage("mingw-w64-ucrt-x86_64-headers-git", exact=True) }}
        - __unix   # [unix]
        - __win    # [win]
      run_constrained:
        - mingw-w64-ucrt-x86_64-crt-git {{ PKG_VERSION }}.*
    test:
      commands:
        - test -f ${PREFIX}/x86_64-w64-mingw32/sysroot/usr/include/pthread.h      # [unix]
        - test -f ${PREFIX}/x86_64-w64-mingw32/sysroot/usr/include/sched.h        # [unix]
    about:
      home: https://www.mingw-w64.org/
      license: MIT AND BSD-3-Clause-Clear
      license_file:
        - mingw-w64-libraries/winpthreads/COPYING
        - COPYING.MinGW-w64/COPYING.MinGW-w64.txt
      summary: |
        MinGW-w64 winpthreads library (mingw-w64)

  - name: libwinpthread
    script: install.sh
    files:
      - Library/bin/libwinpthread-1.dll
    build:
      skip: True  # [not win]
    requirements:
      build:
        - gcc_bootstrap_win-64
        - make
      host:
        - ucrt
      run:
        - ucrt
      run_constrained:
        - msys2-conda-epoch <0.0a0
        - pthreads-win32 <0.0a0
    about:
      home: https://www.mingw-w64.org/
      license: MIT AND BSD-3-Clause-Clear
      license_file:
        - mingw-w64-libraries/winpthreads/COPYING
        - COPYING.MinGW-w64/COPYING.MinGW-w64.txt
      summary: |
        MinGW-w64 winpthreads library (mingw-w64)

  - name: mingw-w64-ucrt-x86_64-crt-git
    script: install.sh
    files:
      - x86_64-w64-mingw32/sysroot/usr/include/*.c
      - x86_64-w64-mingw32/sysroot/usr/lib
      - Library/x86_64-w64-mingw32/sysroot/usr/include/*.c
      - Library/x86_64-w64-mingw32/sysroot/usr/lib
    build:
      noarch: generic
    requirements:
      build:
        - gcc_bootstrap_win-64
        - make
      host:
        # Add a package here to prevent build host merge
        - tzdata
      run:
        - __unix   # [unix]
        - __win    # [win]
        - {{ pin_subpackage("mingw-w64-ucrt-x86_64-headers-git", exact=True) }}
      run_constrained:
        - mingw-w64-ucrt-x86_64-winpthreads-git {{ PKG_VERSION }}.*
    about:
      home: https://www.mingw-w64.org/
      license: ZPL-2.1
      license_file: COPYING
      summary: |
        MinGW-w64 CRT for Windows (mingw-w64)

  - name: m2w64-sysroot_win-64
    script: copy.sh
    build:
      noarch: generic
      run_exports:
        strong:
          - libwinpthread >={{ PKG_VERSION }}
    requirements:
      build:
        - gcc_bootstrap_win-64
        - make
      host:
        # Add a package here to prevent build host merge
        - tzdata
        - ucrt     # [win]
      run:
        - __unix   # [unix]
        - __win    # [win]
        - ucrt     # [win]
        - mingw-w64-ucrt-x86_64-windows-default-manifest
        - {{ pin_subpackage("mingw-w64-ucrt-x86_64-crt-git", exact=True) }}
        - {{ pin_subpackage("mingw-w64-ucrt-x86_64-headers-git", exact=True) }}
        - {{ pin_subpackage("mingw-w64-ucrt-x86_64-winpthreads-git", exact=True) }}
    test:
      commands:
        - test -f ${PREFIX}/x86_64-w64-mingw32/sysroot/usr/include/pthread.h      # [unix]
        - test -f ${PREFIX}/x86_64-w64-mingw32/sysroot/ucrt64/include/pthread.h   # [unix]
    about:
      home: https://mingw-w64.sourceforge.io/
      summary: |
        MinGW-w64 sysroot for Windows

about:
  home: https://github.com/mingw-w64/mingw-64
  summary: 'A complete runtime environment for GCC & LLVM for 32 and 64 bit windows'
  license: ZPL-2.1 AND LGPL-2.1-or-later and MIT AND BSD-3-Clause-Clear
  license_file:
    - COPYING
    - COPYING.MinGW-w64/COPYING.MinGW-w64.txt


extra:
  recipe-maintainers:
    - isuruf
